### ISSUE TITLE
Won't locate file name for a show

### ISSUE THREAD

**Issue by Spaceherpe** [tvrenamer/tvrenamer#135]
I've been ignoring this problem for quite some time, but figured I'd notify you guys here. The Big Bang Theory won't locate the correct show name and rename the file. I've always had to do this manually.

The same goes for all of my shows that are M.A.R.V.E.L.. Any chance there's a fix for this?

**Comment by daveharris** [comment]
Hi,
We have already fixed the M.A.R.V.E.L. issue in #108 - but it's yet to released. I can't quite remember why we are still on `v0.7.2` and `v0.8` hasn't been released yet. It's been so long.

Can you give us the filename of a The Big Bang Theory episode which doesn't rename? It should be working fine

**Comment by Spaceherpe** [comment]
I have found that any shows that do not have the "S" or "E" like the file
name listed here the.big.bang.theory.1020.hdtv-lol will not work. Once I
personally add the S or E, it will. This is frustrating, but a minor
inconvenience. I'm not sure if you guys were already aware of this or not.

**Comment by vipuldelwadia** [comment]
We've had issues in the past with filenames like that, but I wasn't aware that it's still an issue - something to investigate now that we have a test case for it.

**Comment by Spaceherpe** [comment]
Glad I could help!

**Comment by vipuldelwadia** [comment]
This is the TheTVDB v1 API shutdown. Releases before 1.0b5 looked up episodes there, and that API is retired, so those versions cannot find any show information at all.

1.0 uses TVmaze instead: https://github.com/tvrenamer/tvrenamer/releases/tag/v1.0

Closing. If you still see this on 1.0, please reopen or open a new issue with an example filename.
